-- ============================================================
-- Fase 0 · 0000 — Tabelas de CONTEÚDO (criação do zero, projeto novo)
-- Espelha src/db/schema.ts. IDs com identity (auto-incremento).
-- Ordem de aplicação: 0000 → 0001 → 0002.
-- ============================================================

-- ---------- Hierarquia do quiz (Desafio dos Sábios) ----------
create table if not exists public.quiz_subjects (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_grades (
  id         bigint generated by default as identity primary key,
  name       varchar(50) not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_assessments (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null,
  grade_id   bigint not null references public.quiz_grades(id) on delete cascade,
  subject_id bigint not null references public.quiz_subjects(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (name, grade_id, subject_id)
);

create table if not exists public.quiz_topics (
  id            bigint generated by default as identity primary key,
  subject_id    bigint not null references public.quiz_subjects(id) on delete cascade,
  grade_id      bigint references public.quiz_grades(id) on delete set null,
  assessment_id bigint references public.quiz_assessments(id) on delete set null,
  name          varchar(100) not null,
  created_at    timestamptz not null default now(),
  unique (subject_id, grade_id, assessment_id, name)
);

-- ---------- Questões (3 variantes da BaseQuizQuestion) ----------
create table if not exists public.quiz_questions (
  id                  bigint generated by default as identity primary key,
  topic_id            bigint not null references public.quiz_topics(id) on delete cascade,
  question            text not null,
  options             jsonb,
  answer              text not null,
  type                varchar(30) not null default 'multiple_choice',
  difficulty          varchar(10) not null default 'medium',
  journey             varchar(50) not null default 'Logos',
  explanation         text not null default '',
  cronica_do_guardiao text not null default '',
  tags                jsonb not null default '[]'::jsonb,
  created_at          timestamptz not null default now(),
  has_image           boolean not null default false,
  image_mode          varchar(25) not null default 'none',
  image_url           text,
  image_prompt        text,
  image_alt           varchar(300),
  image               text,
  metadata_json       jsonb not null default '{}'::jsonb,
  source              varchar(20) not null default 'manual'
);

create table if not exists public.quiz_questions_generated (
  id                  bigint generated by default as identity primary key,
  topic_id            bigint not null references public.quiz_topics(id) on delete cascade,
  question            text not null,
  options             jsonb,
  answer              text not null,
  type                varchar(30) not null default 'multiple_choice',
  difficulty          varchar(10) not null default 'medium',
  journey             varchar(50) not null default 'Logos',
  explanation         text not null default '',
  cronica_do_guardiao text not null default '',
  tags                jsonb not null default '[]'::jsonb,
  created_at          timestamptz not null default now(),
  has_image           boolean not null default false,
  image_mode          varchar(25) not null default 'none',
  image_url           text,
  image_prompt        text,
  image_alt           varchar(300),
  image               text,
  metadata_json       jsonb not null default '{}'::jsonb,
  ai_model            varchar(50) not null default 'gemini-2.0-flash'
);

create table if not exists public.quiz_questions_verified (
  id                  bigint generated by default as identity primary key,
  topic_id            bigint not null references public.quiz_topics(id) on delete cascade,
  question            text not null,
  options             jsonb,
  answer              text not null,
  type                varchar(30) not null default 'multiple_choice',
  difficulty          varchar(10) not null default 'medium',
  journey             varchar(50) not null default 'Logos',
  explanation         text not null default '',
  cronica_do_guardiao text not null default '',
  tags                jsonb not null default '[]'::jsonb,
  created_at          timestamptz not null default now(),
  has_image           boolean not null default false,
  image_mode          varchar(25) not null default 'none',
  image_url           text,
  image_prompt        text,
  image_alt           varchar(300),
  image               text,
  metadata_json       jsonb not null default '{}'::jsonb,
  verified_by_id      bigint  -- referência opcional ao revisor (sem FK p/ auth)
);

create table if not exists public.desafio_dos_sabios_questiongenerationcache (
  id                bigint generated by default as identity primary key,
  topic_id          bigint not null references public.quiz_topics(id) on delete cascade,
  difficulty        varchar(10) not null,
  generated_count   integer not null default 0,
  last_generated_at timestamptz not null default now(),
  unique (topic_id, difficulty)
);

-- ---------- Jogos (palavras e metadados) ----------
create table if not exists public.jogos_palavraspellingbee (
  id          bigint generated by default as identity primary key,
  palavra     varchar(100) not null,
  significado text not null,
  ipa         varchar(100) not null default '',
  exemplo     text not null default '',
  serie       varchar(10) not null default '2ano',
  dificuldade varchar(10) not null default 'facil'
);

create table if not exists public.jogos_palavraradix (
  id          bigint generated by default as identity primary key,
  palavra     varchar(100) not null,
  significado text not null default '',
  exemplo     text not null default '',
  dificuldade varchar(20) not null default 'facil'
);

create table if not exists public.jogos_jogo (
  id          bigint generated by default as identity primary key,
  nome        varchar(100) not null,
  slug        varchar(50) not null unique,
  tipo        varchar(20) not null,
  descricao   text not null default '',
  dificuldade varchar(20) not null default '',
  ativo       boolean not null default true
);

create table if not exists public.jogos_conquista (
  id                 bigint generated by default as identity primary key,
  nome               varchar(100) not null,
  descricao          text not null,
  icone              varchar(50) not null,
  pontos_necessarios integer not null default 0,
  tipo               varchar(50) not null
);
