-- ============================================================
-- Fase 2 · 0003 — Gamificação unificada (event-sourced)
-- Substitui os 2 sistemas antigos (PerfilEstudante √ vs UserProgress linear)
-- por UMA curva e UM registro de eventos. Idempotente.
-- ============================================================

-- XP/nível no profile (fonte única de progresso)
alter table public.profiles
  add column if not exists total_xp integer not null default 0,
  add column if not exists level integer not null default 1;

-- Eventos de jogo (fonte da verdade auditável)
create table if not exists public.game_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  game       text not null,          -- 'desafio' | 'spelling-bee' | 'radix' | ...
  type       text not null,          -- 'QUESTION_ANSWERED' | 'SESSION_FINISHED'
  payload    jsonb not null default '{}'::jsonb,
  xp_delta   integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists game_events_user_idx
  on public.game_events (user_id, created_at desc);

-- Curva RPG unificada: nível = floor(sqrt(xp/100)) + 1
create or replace function public.level_for_xp(xp integer)
returns integer language sql immutable as $$
  select greatest(1, floor(sqrt(greatest(xp, 0)::numeric / 100))::int + 1);
$$;

-- Concede XP atomicamente: registra o evento + atualiza o total no profile.
-- SECURITY DEFINER para poder escrever no profile (RLS é own-only).
create or replace function public.award_xp(
  p_game text, p_type text, p_payload jsonb, p_xp integer
)
returns table(total_xp integer, level integer, leveled_up boolean)
language plpgsql security definer set search_path = public as $$
declare
  v_uid       uuid := auth.uid();
  v_old_level int;
  v_total     int;
  v_level     int;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  insert into public.game_events (user_id, game, type, payload, xp_delta)
  values (v_uid, p_game, p_type, coalesce(p_payload, '{}'::jsonb), greatest(p_xp, 0));

  select p.level into v_old_level from public.profiles p where p.id = v_uid;

  update public.profiles p
     set total_xp   = p.total_xp + greatest(p_xp, 0),
         level      = public.level_for_xp(p.total_xp + greatest(p_xp, 0)),
         updated_at = now()
   where p.id = v_uid
   returning p.total_xp, p.level into v_total, v_level;

  return query select v_total, v_level, (v_level > coalesce(v_old_level, 1));
end;
$$;

-- RLS dos eventos: cada um vê/insere apenas os próprios.
alter table public.game_events enable row level security;

drop policy if exists game_events_own_select on public.game_events;
create policy game_events_own_select on public.game_events
  for select using (auth.uid() = user_id);

drop policy if exists game_events_own_insert on public.game_events;
create policy game_events_own_insert on public.game_events
  for insert with check (auth.uid() = user_id);
