# Generated by Django 5.2.4 on 2025-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaseTrivium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        help_text="1 para Gramática, 2 para Lógica, 3 para Retórica"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase do Trivium",
                "verbose_name_plural": "Fases do Trivium",
                "ordering": ["ordem"],
            },
        ),
    ]
