# Generated by Django 5.2.4 on 2025-07-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "componente_frontend",
                    models.CharField(
                        help_text="Nome do componente usado no frontend (ex: 'radixGame', 'spellingBeeChallenge')",
                        max_length=100,
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos",
                        to="jogos.fasetrivium",
                    ),
                ),
            ],
        ),
    ]
