# Generated by Django 5.2.4 on 2025-07-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0002_jogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jogo",
            options={
                "ordering": ["nome"],
                "verbose_name": "Jogo",
                "verbose_name_plural": "Jogos",
            },
        ),
        migrations.RemoveField(
            model_name="jogo",
            name="componente_frontend",
        ),
        migrations.AddField(
            model_name="jogo",
            name="pontua_para_ranking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jogo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("soletracao_pt", "Soletração em Português"),
                    ("soletracao_en", "Spelling Bee"),
                    ("memoria", "Jogo de Memória"),
                    ("associacao", "Jogo de Associação"),
                    ("quiz", "Quiz"),
                    ("outro", "Outro"),
                ],
                default="soletracao_pt",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="dificuldade",
            field=models.CharField(
                choices=[
                    ("basico", "Básico"),
                    ("intermediario", "Intermediário"),
                    ("avancado", "Avançado"),
                ],
                default="basico",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="fase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jogos.fasetrivium"
            ),
        ),
    ]
