# Generated by Django 5.2.4 on 2025-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0003_alter_jogo_options_remove_jogo_componente_frontend_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jogo",
            options={"verbose_name": "Jogo", "verbose_name_plural": "Jogos"},
        ),
        migrations.AddField(
            model_name="jogo",
            name="slug",
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jogo",
            name="dificuldade",
            field=models.CharField(
                choices=[("easy", "Fácil"), ("normal", "Normal"), ("hard", "Difícil")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="pontua_para_ranking",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("soletracao", "Soletração"),
                    ("memoria", "Memória"),
                    ("quiz", "Quiz"),
                    ("arrastar", "Arrastar e Soltar"),
                ],
                max_length=20,
            ),
        ),
    ]
