# Generated by Django 5.2.4 on 2025-07-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0004_alter_jogo_options_jogo_slug_alter_jogo_dificuldade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("soletracao", "Soletração"),
                    ("memoria", "Memória"),
                    ("quiz", "Quiz"),
                    ("arrastar", "Arrastar e Soltar"),
                    ("visualizar", "Visualização"),
                ],
                max_length=20,
            ),
        ),
    ]
