# Generated by Django 5.2.4 on 2025-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0005_alter_jogo_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalavraSpellingBee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palavra", models.CharField(max_length=100)),
                ("frase", models.TextField()),
                ("significado", models.TextField()),
                ("ano", models.CharField(max_length=20)),
            ],
        ),
    ]
