# Generated by Django 5.2.4 on 2025-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0006_palavraspellingbee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogo",
            name="fase",
        ),
        migrations.RemoveField(
            model_name="jogo",
            name="pontua_para_ranking",
        ),
        migrations.RemoveField(
            model_name="palavraspellingbee",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="palavraspellingbee",
            name="frase",
        ),
        migrations.AddField(
            model_name="palavraspellingbee",
            name="exemplo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="palavraspellingbee",
            name="serie",
            field=models.CharField(
                choices=[("2ano", "2º Ano"), ("4ano", "4º Ano")],
                default="2ano",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="dificuldade",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="tipo",
            field=models.CharField(
                choices=[("spellingbee", "Spelling Bee"), ("radix", "Radix")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="FaseTrivium",
        ),
    ]
