# Generated by Django 5.2.4 on 2026-02-18 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_remove_jogo_fase_remove_jogo_pontua_para_ranking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Nome do ícone ou classe CSS', max_length=50)),
                ('pontos_necessarios', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('level', 'Nível'), ('achievement', 'Conquista')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('2ano', '2º Ano'), ('4ano', '4º Ano')], max_length=10)),
                ('xp', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('medalhas', models.ManyToManyField(blank=True, to='jogos.conquista')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuação', models.IntegerField(default=0)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('erros_detalhados', models.JSONField(blank=True, default=dict)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.perfilestudante')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogo')),
            ],
        ),
    ]
