# Generated by Django 5.2.4 on 2026-02-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_conquista_perfilestudante_sessaojogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavraspellingbee',
            name='ipa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
