# Generated by Django 5.2.4 on 2026-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0009_palavraspellingbee_ipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraRadix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100)),
                ('significado', models.TextField(blank=True)),
                ('exemplo', models.TextField(blank=True)),
                ('dificuldade', models.CharField(default='facil', max_length=20)),
            ],
        ),
    ]
