# Generated by Django 5.2.4 on 2026-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_palavraradix'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
