# Generated by Django 5.2.4 on 2026-03-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0011_perfilestudante_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavraspellingbee',
            name='serie',
            field=models.CharField(choices=[('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano')], default='2ano', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilestudante',
            name='serie',
            field=models.CharField(choices=[('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano')], max_length=10),
        ),
    ]
