# Generated by Django 5.2.4 on 2026-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0012_alter_palavraspellingbee_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavraspellingbee',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10),
        ),
        migrations.AlterField(
            model_name='palavraspellingbee',
            name='exemplo',
            field=models.TextField(blank=True, help_text='Frase de exemplo em inglês'),
        ),
        migrations.AlterField(
            model_name='palavraspellingbee',
            name='ipa',
            field=models.CharField(blank=True, help_text='Alfabeto Fonético Internacional', max_length=100),
        ),
        migrations.AlterField(
            model_name='palavraspellingbee',
            name='serie',
            field=models.CharField(choices=[('1ano', '1º Ano'), ('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano'), ('6ano', '6º Ano'), ('7ano', '7º Ano'), ('8ano', '8º Ano'), ('9ano', '9º Ano')], default='2ano', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilestudante',
            name='serie',
            field=models.CharField(choices=[('1ano', '1º Ano'), ('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano'), ('6ano', '6º Ano'), ('7ano', '7º Ano'), ('8ano', '8º Ano'), ('9ano', '9º Ano')], max_length=10),
        ),
    ]
