-- ============================================================================
-- ARKANOS 2.0 — BOOTSTRAP COMPLETO (cole no Supabase → SQL Editor → Run)
-- Cria: tabelas de conteúdo + profiles + trigger de signup + RLS.
-- Idempotente (pode rodar mais de uma vez sem erro).
-- ============================================================================

-- ============================ CONTEÚDO ======================================

create table if not exists public.quiz_subjects (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_grades (
  id         bigint generated by default as identity primary key,
  name       varchar(50) not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_assessments (
  id         bigint generated by default as identity primary key,
  name       varchar(100) not null,
  grade_id   bigint not null references public.quiz_grades(id) on delete cascade,
  subject_id bigint not null references public.quiz_subjects(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (name, grade_id, subject_id)
);

create table if not exists public.quiz_topics (
  id            bigint generated by default as identity primary key,
  subject_id    bigint not null references public.quiz_subjects(id) on delete cascade,
  grade_id      bigint references public.quiz_grades(id) on delete set null,
  assessment_id bigint references public.quiz_assessments(id) on delete set null,
  name          varchar(100) not null,
  created_at    timestamptz not null default now(),
  unique (subject_id, grade_id, assessment_id, name)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.quiz_topics(id) on delete cascade,
  question text not null,
  options jsonb,
  answer text not null,
  type varchar(30) not null default 'multiple_choice',
  difficulty varchar(10) not null default 'medium',
  journey varchar(50) not null default 'Logos',
  explanation text not null default '',
  cronica_do_guardiao text not null default '',
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  has_image boolean not null default false,
  image_mode varchar(25) not null default 'none',
  image_url text, image_prompt text, image_alt varchar(300), image text,
  metadata_json jsonb not null default '{}'::jsonb,
  source varchar(20) not null default 'manual'
);

create table if not exists public.quiz_questions_generated (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.quiz_topics(id) on delete cascade,
  question text not null,
  options jsonb,
  answer text not null,
  type varchar(30) not null default 'multiple_choice',
  difficulty varchar(10) not null default 'medium',
  journey varchar(50) not null default 'Logos',
  explanation text not null default '',
  cronica_do_guardiao text not null default '',
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  has_image boolean not null default false,
  image_mode varchar(25) not null default 'none',
  image_url text, image_prompt text, image_alt varchar(300), image text,
  metadata_json jsonb not null default '{}'::jsonb,
  ai_model varchar(50) not null default 'gemini-2.0-flash'
);

create table if not exists public.quiz_questions_verified (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.quiz_topics(id) on delete cascade,
  question text not null,
  options jsonb,
  answer text not null,
  type varchar(30) not null default 'multiple_choice',
  difficulty varchar(10) not null default 'medium',
  journey varchar(50) not null default 'Logos',
  explanation text not null default '',
  cronica_do_guardiao text not null default '',
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  has_image boolean not null default false,
  image_mode varchar(25) not null default 'none',
  image_url text, image_prompt text, image_alt varchar(300), image text,
  metadata_json jsonb not null default '{}'::jsonb,
  verified_by_id bigint
);

create table if not exists public.desafio_dos_sabios_questiongenerationcache (
  id                bigint generated by default as identity primary key,
  topic_id          bigint not null references public.quiz_topics(id) on delete cascade,
  difficulty        varchar(10) not null,
  generated_count   integer not null default 0,
  last_generated_at timestamptz not null default now(),
  unique (topic_id, difficulty)
);

create table if not exists public.jogos_palavraspellingbee (
  id bigint generated by default as identity primary key,
  palavra varchar(100) not null,
  significado text not null,
  ipa varchar(100) not null default '',
  exemplo text not null default '',
  serie varchar(10) not null default '2ano',
  dificuldade varchar(10) not null default 'facil'
);

create table if not exists public.jogos_palavraradix (
  id bigint generated by default as identity primary key,
  palavra varchar(100) not null,
  significado text not null default '',
  exemplo text not null default '',
  dificuldade varchar(20) not null default 'facil'
);

create table if not exists public.jogos_jogo (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  slug varchar(50) not null unique,
  tipo varchar(20) not null,
  descricao text not null default '',
  dificuldade varchar(20) not null default '',
  ativo boolean not null default true
);

create table if not exists public.jogos_conquista (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  descricao text not null,
  icone varchar(50) not null,
  pontos_necessarios integer not null default 0,
  tipo varchar(50) not null
);

-- ============================ AUTH: profiles ================================

create table if not exists public.profiles (
  id              uuid primary key references auth.users (id) on delete cascade,
  display_name    text,
  serie           text,
  data_nascimento date,
  role            text not null default 'student',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, serie, data_nascimento)
  values (
    new.id,
    new.raw_user_meta_data ->> 'display_name',
    new.raw_user_meta_data ->> 'serie',
    nullif(new.raw_user_meta_data ->> 'data_nascimento', '')::date
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================ RLS ==========================================

alter table public.profiles enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select using (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles
  for insert with check (auth.uid() = id);

-- Conteúdo: leitura pública; escrita só service_role (que ignora RLS).
do $$
declare
  t text;
  content_tables text[] := array[
    'quiz_subjects', 'quiz_grades', 'quiz_assessments', 'quiz_topics',
    'quiz_questions', 'quiz_questions_generated', 'quiz_questions_verified',
    'jogos_palavraspellingbee', 'jogos_palavraradix', 'jogos_jogo', 'jogos_conquista'
  ];
begin
  foreach t in array content_tables loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists %I on public.%I;', t || '_read', t);
    execute format('create policy %I on public.%I for select using (true);', t || '_read', t);
  end loop;
end $$;
