# Generated by Django 5.2.4 on 2026-03-06 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_dos_sabios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_grades',
            },
        ),
        migrations.CreateModel(
            name='QuizAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='desafio_dos_sabios.quizsubject')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='desafio_dos_sabios.quizgrade')),
            ],
            options={
                'db_table': 'quiz_assessments',
                'unique_together': {('name', 'grade', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='quiztopic',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='desafio_dos_sabios.quizassessment'),
        ),
        migrations.AlterUniqueTogether(
            name='quiztopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quiztopic',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='desafio_dos_sabios.quizgrade'),
        ),
        migrations.AlterUniqueTogether(
            name='quiztopic',
            unique_together={('subject', 'grade', 'assessment', 'name')},
        ),
    ]
