# Generated by Django 5.2.4 on 2026-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_dos_sabios', '0002_quizgrade_quizassessment_quiztopic_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.TextField(blank=True, help_text='URL ou base64 da imagem de suporte', null=True),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='image',
            field=models.TextField(blank=True, help_text='URL ou base64 da imagem de suporte', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='image',
            field=models.TextField(blank=True, help_text='URL ou base64 da imagem de suporte', null=True),
        ),
    ]
