# Generated by Django 5.1.6 on 2026-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_dos_sabios', '0003_quizquestion_image_quizquestiongenerated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='cronica_do_guardiao',
            field=models.TextField(blank=True, help_text='Texto narrativo pós-resposta: fato histórico, curiosidade ou contexto geográfico.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo (acessibilidade)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_mode',
            field=models.CharField(choices=[('none', 'Sem imagem'), ('uploaded_asset', 'Asset Enviado'), ('generated_asset', 'Gerado por IA'), ('external_reference', 'Referência Externa')], default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt de geração de imagem via IA', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL da imagem após geração/upload', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extras: id_original, tema, referência de mapa, etc.'),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='cronica_do_guardiao',
            field=models.TextField(blank=True, help_text='Texto narrativo pós-resposta: fato histórico, curiosidade ou contexto geográfico.'),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo (acessibilidade)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='image_mode',
            field=models.CharField(choices=[('none', 'Sem imagem'), ('uploaded_asset', 'Asset Enviado'), ('generated_asset', 'Gerado por IA'), ('external_reference', 'Referência Externa')], default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt de geração de imagem via IA', null=True),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL da imagem após geração/upload', null=True),
        ),
        migrations.AddField(
            model_name='quizquestiongenerated',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extras: id_original, tema, referência de mapa, etc.'),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='cronica_do_guardiao',
            field=models.TextField(blank=True, help_text='Texto narrativo pós-resposta: fato histórico, curiosidade ou contexto geográfico.'),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo (acessibilidade)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='image_mode',
            field=models.CharField(choices=[('none', 'Sem imagem'), ('uploaded_asset', 'Asset Enviado'), ('generated_asset', 'Gerado por IA'), ('external_reference', 'Referência Externa')], default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt de geração de imagem via IA', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL da imagem após geração/upload', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionverified',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extras: id_original, tema, referência de mapa, etc.'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.TextField(blank=True, help_text='Campo legado: URL ou base64', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('image_multiple_choice', 'Múltipla Escolha com Imagem'), ('map_analysis', 'Análise de Mapa'), ('diagram_analysis', 'Análise de Diagrama'), ('visual_interpretation', 'Interpretação Visual'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], default='multiple_choice', max_length=30),
        ),
        migrations.AlterField(
            model_name='quizquestiongenerated',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestiongenerated',
            name='image',
            field=models.TextField(blank=True, help_text='Campo legado: URL ou base64', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestiongenerated',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('image_multiple_choice', 'Múltipla Escolha com Imagem'), ('map_analysis', 'Análise de Mapa'), ('diagram_analysis', 'Análise de Diagrama'), ('visual_interpretation', 'Interpretação Visual'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], default='multiple_choice', max_length=30),
        ),
        migrations.AlterField(
            model_name='quizquestionverified',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestionverified',
            name='image',
            field=models.TextField(blank=True, help_text='Campo legado: URL ou base64', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestionverified',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('image_multiple_choice', 'Múltipla Escolha com Imagem'), ('map_analysis', 'Análise de Mapa'), ('diagram_analysis', 'Análise de Diagrama'), ('visual_interpretation', 'Interpretação Visual'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], default='multiple_choice', max_length=30),
        ),
    ]
