export const palavras_4ano = [
{ word: "about", meaning: "On the subject of something.", frase: "We talked about animals." },
        { word: "above", meaning: "At a higher place.", frase: "The bird flew above the trees." },
        { word: "accident", meaning: "Something bad that happens unexpectedly.", frase: "He had a bike accident." },
        { word: "across", meaning: "From one side to the other.", frase: "She walked across the street." },
        { word: "address", meaning: "Where someone lives.", frase: "I wrote my address on the envelope." },
        { word: "afraid", meaning: "Feeling fear or worry.", frase: "She is afraid of the dark." },
        { word: "again", meaning: "One more time.", frase: "Please say it again." },
        { word: "against", meaning: "In opposition to something.", frase: "They played against the other team." },
        { word: "airplane", meaning: "A flying vehicle with wings.", frase: "We traveled by airplane." },
        { word: "always", meaning: "All the time.", frase: "He always brushes his teeth." },
        { word: "angry", meaning: "Feeling mad or upset.", frase: "She was angry about the mess." },
        { word: "animal", meaning: "A living thing that is not a plant.", frase: "The lion is a wild animal." },
        { word: "another", meaning: "One more or different.", frase: "May I have another cookie?" },
        { word: "answer", meaning: "A reply to a question.", frase: "I know the answer!" },
        { word: "apple", meaning: "A red or green fruit.", frase: "I ate an apple for lunch." },
        { word: "around", meaning: "In a circle or nearby.", frase: "We walked around the park." },
        { word: "arrive", meaning: "To reach a place.", frase: "What time will you arrive?" },
        { word: "ask", meaning: "To say something to get an answer.", frase: "I will ask a question." },
        { word: "aunt", meaning: "Your mom or dad’s sister.", frase: "My aunt is visiting today." },
        { word: "autumn", meaning: "The season between summer and winter.", frase: "Leaves fall in autumn." },
        { word: "baby", meaning: "A very young child.", frase: "The baby is sleeping." },
        { word: "back", meaning: "The rear part of something.", frase: "He sat at the back of the room." },
        { word: "ball", meaning: "A round toy for playing.", frase: "We played with a ball." },
        { word: "banana", meaning: "A long yellow fruit.", frase: "Bananas grow on trees." },
        { word: "bathroom", meaning: "A room with a toilet and sink.", frase: "I need to use the bathroom." },
        { word: "beautiful", meaning: "Very pretty or nice to look at.", frase: "The flowers are beautiful." },
        { word: "because", meaning: "The reason for something.", frase: "I’m happy because it’s my birthday." },
        { word: "before", meaning: "Earlier than something else.", frase: "Wash your hands before eating." },
        { word: "begin", meaning: "To start something.", frase: "Let’s begin the lesson." },
        { word: "behind", meaning: "At the back of something.", frase: "The cat is behind the sofa." },
        { word: "believe", meaning: "To think something is true.", frase: "I believe in kindness." },
        { word: "below", meaning: "In a lower place.", frase: "The shoes are below the bed." },
        { word: "best", meaning: "Better than all others.", frase: "She is my best friend." },
        { word: "better", meaning: "Improved or more good.", frase: "I feel better today." },
        { word: "between", meaning: "In the space separating two things.", frase: "The ball is between the chairs." },
        { word: "big", meaning: "Large in size.", frase: "That dog is very big." },
        { word: "birthday", meaning: "The day you were born.", frase: "My birthday is in July." },
        { word: "black", meaning: "The darkest color.", frase: "She wore a black dress." },
        { word: "blue", meaning: "A color like the sky or ocean.", frase: "His eyes are blue." },
        { word: "boat", meaning: "A vehicle that floats on water.", frase: "We went fishing in a boat." },
        { word: "body", meaning: "All the parts of a person or animal.", frase: "Exercise is good for your body." },
        { word: "book", meaning: "A set of written or printed pages.", frase: "She read a new book." },
        { word: "both", meaning: "Two things together.", frase: "I like both cats and dogs." },
        { word: "bottle", meaning: "A container for holding liquids.", frase: "He drank a bottle of water." },
        { word: "box", meaning: "A container with flat sides.", frase: "The toys are in the box." },
        { word: "boy", meaning: "A male child.", frase: "The boy is playing soccer." },
        { word: "bread", meaning: "A baked food made from flour.", frase: "I like bread with butter." },
        { word: "break", meaning: "To separate into pieces or pause.", frase: "Let’s take a short break." },
        { word: "bring", meaning: "To carry something to a place.", frase: "Please bring your homework." },
        { word: "brother", meaning: "A male sibling.", frase: "My brother is older than me." },
        { word: "brown", meaning: "A color like chocolate or wood.", frase: "She has brown hair." },
        { word: "build", meaning: "To make something by putting parts together.", frase: "We will build a sandcastle." },
        { word: "bus", meaning: "A big vehicle that carries many people.", frase: "I go to school by bus." },
        { word: "buy", meaning: "To get something by paying money.", frase: "I will buy a toy." },
        { word: "cake", meaning: "A sweet baked dessert.", frase: "He had chocolate cake for dessert." },
        { word: "call", meaning: "To use a phone or shout a name.", frase: "I will call my friend." },
        { word: "can", meaning: "To be able to do something.", frase: "I can ride a bike." },
        { word: "car", meaning: "A vehicle with four wheels.", frase: "She drove a red car." },
        { word: "carry", meaning: "To hold and move something.", frase: "He will carry the bag." },
        { word: "cat", meaning: "A small animal that says meow.", frase: "The cat is on the sofa." },
        { word: "chair", meaning: "A seat with legs and a back.", frase: "She sat on the chair." },
        { word: "change", meaning: "To make something different.", frase: "Let’s change the color." },
        { word: "chicken", meaning: "A bird or its meat.", frase: "We had chicken for lunch." },
        { word: "child", meaning: "A young person.", frase: "The child is learning to read." },
        { word: "clean", meaning: "Free from dirt or mess.", frase: "Wash your hands and keep them clean." },
        { word: "climb", meaning: "To go up something like a tree or stairs.", frase: "He can climb the ladder." },
        { word: "close", meaning: "To shut something.", frase: "Please close the door." },
        { word: "cloud", meaning: "A white or gray shape in the sky.", frase: "That cloud looks like a rabbit!" },
        { word: "coat", meaning: "A warm piece of clothing.", frase: "She wore a red coat." },
        { word: "cold", meaning: "Having a low temperature.", frase: "The water is very cold." },
        { word: "color", meaning: "The shade or appearance of something.", frase: "My favorite color is green." },
        { word: "come", meaning: "To move toward someone or something.", frase: "Come here, please!" },
        { word: "cookie", meaning: "A small sweet baked treat.", frase: "He ate a chocolate chip cookie." },
        { word: "cool", meaning: "A little cold or calm and stylish.", frase: "It’s cool outside today." },
        { word: "corner", meaning: "The point where two sides meet.", frase: "He stood in the corner." },
        { word: "cow", meaning: "A farm animal that gives milk.", frase: "The cow is eating grass." },
        { word: "cry", meaning: "To shed tears when sad or hurt.", frase: "The baby began to cry." },
        { word: "cup", meaning: "A small container for drinking.", frase: "She drank tea from a cup." },
        { word: "cut", meaning: "To divide something using a sharp tool.", frase: "He will cut the paper." },
        { word: "dance", meaning: "To move to music.", frase: "We love to dance at parties." },
        { word: "day", meaning: "The time from morning to night.", frase: "Today is a sunny day." },
        { word: "dear", meaning: "Loved or cherished.", frase: "My grandma is very dear to me." },
        { word: "desk", meaning: "A piece of furniture used for writing or working.", frase: "He sat at his desk." },
        { word: "dictionary", meaning: "A book that gives meanings of words.", frase: "I looked it up in the dictionary." },
        { word: "dinner", meaning: "The main meal of the evening.", frase: "We had pasta for dinner." },
        { word: "dog", meaning: "A common pet that barks.", frase: "The dog is running in the yard." },
        { word: "door", meaning: "An entry or exit that opens and closes.", frase: "She knocked on the door." },
        { word: "down", meaning: "Toward a lower place.", frase: "The ball rolled down the hill." },
        { word: "draw", meaning: "To make a picture with a pencil or pen.", frase: "I will draw a house." },
        { word: "drink", meaning: "To take in liquid.", frase: "He likes to drink juice." },
        { word: "drive", meaning: "To control a car or vehicle.", frase: "She can drive to school." },
        { word: "duck", meaning: "A bird that swims and quacks.", frase: "The duck is in the pond." },
        { word: "each", meaning: "Every one of two or more.", frase: "Each student has a book." },
        { word: "ear", meaning: "The part of the body used to hear.", frase: "He covered his ear." },
        { word: "early", meaning: "Before the usual time.", frase: "She woke up early today." },
        { word: "earth", meaning: "The planet we live on.", frase: "The earth goes around the sun." },
        { word: "eat", meaning: "To take food into the mouth and swallow it.", frase: "We eat lunch at noon." },
        { word: "egg", meaning: "A round food from a bird.", frase: "He had an egg for breakfast." },
        { word: "eight", meaning: "The number after seven.", frase: "I have eight pencils." },
        { word: "elephant", meaning: "A large gray animal with a trunk.", frase: "The elephant is big and smart." },
        { word: "end", meaning: "The final part of something.", frase: "We reached the end of the story." },
        { word: "enough", meaning: "As much as needed.", frase: "Do you have enough water?" },
        { word: "every", meaning: "All the individual members of a group.", frase: "Every student must read the book." },
        { word: "eye", meaning: "Part of the body used to see.", frase: "She has blue eyes." },
        { word: "face", meaning: "The front part of the head.", frase: "Wash your face in the morning." },
        { word: "family", meaning: "A group of people related to each other.", frase: "I love my family." },
        { word: "farm", meaning: "A place where animals and crops are raised.", frase: "My uncle works on a farm." },
        { word: "fast", meaning: "Quick or in a short time.", frase: "He runs very fast." },
        { word: "father", meaning: "Another word for dad.", frase: "My father is very kind." },
        { word: "favorite", meaning: "Most liked.", frase: "Blue is my favorite color." },
        { word: "feel", meaning: "To sense something through touch or emotions.", frase: "I feel happy today." },
        { word: "feet", meaning: "The plural of foot.", frase: "My feet are tired." },
        { word: "find", meaning: "To discover something that was lost.", frase: "Can you find my keys?" },
        { word: "fine", meaning: "Good or okay.", frase: "I'm feeling fine." },
        { word: "finger", meaning: "One of the five parts on each hand.", frase: "I hurt my finger." },
        { word: "finish", meaning: "To complete something.", frase: "I will finish my homework soon." },
        { word: "fire", meaning: "Heat and light from something burning.", frase: "The fire kept us warm." },
        { word: "fish", meaning: "An animal that lives in water.", frase: "He caught a big fish." },
        { word: "floor", meaning: "The bottom surface of a room.", frase: "The floor is clean." },
        { word: "flower", meaning: "A colorful part of a plant.", frase: "She picked a yellow flower." },
        { word: "fly", meaning: "To move through the air.", frase: "Birds fly in the sky." },
        { word: "food", meaning: "What people and animals eat.", frase: "We brought food for the picnic." },
        { word: "foot", meaning: "The part of the body below the ankle.", frase: "I stepped on a rock with my foot." },
        { word: "forest", meaning: "A large area filled with trees.", frase: "The forest is full of animals." },
        { word: "forget", meaning: "To not remember something.", frase: "Don’t forget your backpack!" },
        { word: "four", meaning: "The number after three.", frase: "She has four pets." },
        { word: "friend", meaning: "Someone you like and trust.", frase: "He is my best friend." },
        { word: "frog", meaning: "A small animal that jumps and croaks.", frase: "The frog is green and wet." },
        { word: "fruit", meaning: "Sweet food that grows on trees or plants.", frase: "She eats fruit every day." },
        { word: "funny", meaning: "Causing laughter or amusement.", frase: "That movie was very funny." }
];
