# Generated by Django 5.2.4 on 2026-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('journey', models.CharField(default='Logos', max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
