# Generated by Django 5.2.4 on 2026-03-04 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_dos_sabios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('journey', models.CharField(default='Logos', max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.CharField(default='gemini-2.0-flash', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'Gerada por IA'), ('teacher_added', 'Adicionada por Professor')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionGenerationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('generated_count', models.IntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('topic', 'subject', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('true_false', 'Verdadeiro ou Falso'), ('short_answer', 'Resposta Curta'), ('ordering', 'Ordenação')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('journey', models.CharField(default='Logos', max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
