# Generated by Django 5.2.4 on 2026-03-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('worldview_mode', models.CharField(default='christian', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_to_close', 'Ready to Close'), ('published_internal', 'Published Internal')], default='draft', max_length=50)),
                ('current_page_count', models.IntegerField(default=0)),
                ('target_page_range', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ark_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('ebook', 'eBook')], max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='ark.storyproject')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('visual_traits', models.TextField(blank=True, null=True)),
                ('moral_arc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ark.storyproject')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_book_code', models.CharField(max_length=100, unique=True)),
                ('isbn_status', models.CharField(default='pendente', max_length=50)),
                ('catalog_record_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_info', to='ark.storyproject')),
            ],
        ),
        migrations.CreateModel(
            name='StoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cover', 'Cover'), ('scene', 'Scene'), ('reference_upload', 'Reference Upload'), ('character_sheet', 'Character Sheet')], max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ark.storyproject')),
            ],
        ),
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(blank=True, null=True)),
                ('ark_questions', models.TextField(blank=True, null=True)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('illustration_prompt', models.TextField(blank=True, null=True)),
                ('illustration_asset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_range_start', models.IntegerField(default=0)),
                ('page_range_end', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ark.storyproject')),
            ],
        ),
    ]
